#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "example"
name = "Example app"
description.en = "Lightweight torrent streaming application"
description.fr = "Application légère de streaming torrent"

version = "1.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "free"
website = "https://example.com"
demo = "https://demo.example.com"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/hotheadhacker/seedbox-lite"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/hotheadhacker/seedbox-lite/archive/6a89d19747e1b050ea5cc1d12265d5e97f7d38d7.tar.gz"
    sha256 = "52dbcfc6c7d45a984bab912a95a4c16713b1f667fb57e53dee621b6885abdf3f"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
